home/urls.py
from django.urls import path
from .views import HomeView
app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

myfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('summernote/', include('django_summernote.urls'))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    parent = models.ForeignKey(
        'self', on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='category', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categories")

    def __str__(self):
        return self.name


class Post(models.Model):
    POST_STATUS = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category,on_delete=models.SET_NULL, blank=True, null=True, related_name='post_category')
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    tags = TaggableManager()
    image = models.ImageField(upload_to='posts')
    status = models.CharField(max_length=20, choices=POST_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = ("Post")
        verbose_name_plural = ("Posts")

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''

        return url

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='comment_post')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Comment_detail", kwargs={"pk": self.pk})

home/models.py
from django import urls
from django.db import models
from django.db.models.base import Model
from django.urls import reverse
# Create your models here.
class MyService(models.Model):

    name = models.CharField(max_length=50)
    short_description = models.TextField(max_length=300,blank=True)
    description = models.TextField(blank=True)
    service_image = models.ImageField(upload_to="service/")


    class Meta:
        verbose_name = "My Service"
        verbose_name_plural = "My Services"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Service_detail", kwargs={"pk": self.pk})

    def imageURL(self):
        try:
            url = self.service_image.url
        except:
            url = ''

        return url

class MyProject(models.Model):

    title = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    project_url = models.URLField(max_length=200, blank=True)
    project_image = models.ImageField(upload_to="service/", blank=True)

    class Meta:
        verbose_name = "MyProject"
        verbose_name_plural = "MyProjects"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("MyProject_detail", kwargs={"pk": self.pk})

    
    def imageURL(self):
        try:
            url = self.project_image.url
        except:
            url = ''

        return url

blog/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from home.models import MyProject, MyService
from django.shortcuts import render
from django.views.generic import View
from blog.models import Post
# Create your views here.
class HomeView(View):
    def get(self, request):
        carousel_posts = Post.objects.all().order_by('-id')[:4]
        services = MyService.objects.all()
        projects = MyProject.objects.all()[:3]
        context = {
            'posts': carousel_posts,
            'services': services,
            'projects': projects
        }
        return render(request, 'home/index.html',context)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Carousel Template · Rahidul Islam</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">

    

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'carousel.css' %}" rel="stylesheet">
  </head>
  <body>
    
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:home' %}">Rahidul's Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Service</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Portfolio</a>
          </li>
          
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>

<main>
{% block main_content %}
  
{% endblock main_content %}
  


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>


    <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

      
  </body>
</html>

templates/home/index.html
{% extends "base.html" %}
{% load static %}

{% block main_content %}
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        {% for post in posts %}
        <div class="carousel-item {% if forloop.first %} active {% endif %}">
            
            <img class="bd-placeholder-img" width="100%" height="100%" src="{{ post.imageURL }}" alt="{{ post.title }}" >
            <div class="container">
              <div class="carousel-caption">
                <h1>a{{ post.title }}</h1>
                <p>{{ post.content|truncatewords:"20" }}</p>
                <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
              </div>
            </div>
          </div>
        {% endfor %}
      
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing my-10">
    <div class="row justify-content-center my-3">
      <div class="col">
        <h2 class="text-center">My Service</h2>
      </div>
    </div>
    <!-- Three columns of text below the carousel -->
    <div class="row">
      {% for service in services %}
      <div class="col-lg-4">
       
        <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{{ service.imageURL }}" alt="{{ service.name }}">
        <h2>{{ service.name}}</h2>
        <p>{{service.short_description }}</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      {% endfor %}
      
      
    </div><!-- /.row -->

<div class="container">
  <div class="row justify-content-center my-3">
    <div class="col">
      <h2 class="text-center">My Recent Porjects</h2>
    </div>
  </div>
</div>
    <!-- START THE FEATURETTES -->
  {% for project in projects %}
  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7 {% if forloop.counter == 2 %} order-md-2 {% endif %}">
      <h2 class="featurette-heading"><a href="{{ project.project_url }}">{{ project.title }}</a></h2>
      <p class="lead">{{ project.description }}</p>
    </div>
    <div class="col-md-5 {% if forloop.counter == 2 %} order-md-1 {% endif %}">
      
      <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="{{ project.imageURL }}" alt="{{ project.title }}">
    </div>
  </div>
  {% endfor %}


    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->
{% endblock main_content %}